version: '3.8'

services:
  # Axon Server
  axon-server:
    image: axoniq/axonserver:latest
    container_name: axon-server
    ports:
      - "8024:8024" # HTTP Dashboard
      - "8124:8124" # Command/Event/Query communication
    volumes:
      - axon-data:/data # Persistent storage for Axon Server
      - axon-config:/config # Axon Server configuration (if needed)
    networks:
      - app-network

  # Order Service
  order-service:
    image: order-service:latest
    container_name: order-service
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AXON_SERVER_HOST: axon-server
      AXON_SERVER_PORT: 8124
    depends_on:
      - axon-server
      - order-db
    networks:
      - app-network

  # Order Database
  order-db:
    image: postgres:15
    container_name: order-db
    environment:
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpassword
      POSTGRES_DB: orderdb
    ports:
      - "5433:5432"
    networks:
      - app-network

  # Discount Service
  discount-service:
    image: discount-service:latest
    container_name: discount-service
    build:
      context: .
      dockerfile: discount-service/Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AXON_SERVER_HOST: axon-server
      AXON_SERVER_PORT: 8124
    depends_on:
      - axon-server
      - discount-db
    networks:
      - app-network

  # Discount Database
  discount-db:
    image: postgres:15
    container_name: discount-db
    environment:
      POSTGRES_USER: discountuser
      POSTGRES_PASSWORD: discountpassword
      POSTGRES_DB: discountdb
    ports:
      - "5434:5432"
    networks:
      - app-network

  # Payment Service
  payment-service:
    image: payment-service:latest
    container_name: payment-service
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AXON_SERVER_HOST: axon-server
      AXON_SERVER_PORT: 8124
    depends_on:
      - axon-server
      - payment-db
    networks:
      - app-network

  # Payment Database
  payment-db:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpassword
      POSTGRES_DB: paymentdb
    ports:
      - "5435:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  axon-data:
  axon-config: