spring:
  datasource:
    url: jdbc:h2:mem:discountdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

axon:
  axonserver:
    servers: localhost:8124

server:
  port: 8082
