spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:postgresql://localhost:5432/axon
    username: postgres
    password: hamidreza80
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.axonframework: DEBUG
axon:
  axonserver:
    servers: localhost:8124
    context: default
    component-name: discount-service
  serializer:
    general: jackson


server:
  port: 8082
