spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:discountdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
logging:
  level:
    org.axonframework: DEBUG
axon:
  axonserver:
    servers: localhost:8124
    context: default
    component-name: discount-service
  serializer:
    general: jackson


server:
  port: 8082
