spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/axon
    username: postgres
    password: hamidreza80
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.axonframework: DEBUG
axon:
  eventhandling:
    processors:
      SagaProcessor:
        mode: tracking
  saga:
    store: jpa
  axonserver:
    servers: localhost:8124
    context: default
    component-name: order-service
    enabled: true
  serializer:
    general: jackson



server:
  port: 8081
