spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/axon
    username: postgres
    password: hamidreza80
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.axonframework: DEBUG
    com.example.restaurant: DEBUG

axon:
  eventhandling:
    processors:
      RestaurantProcessor:
        mode: tracking
  axonserver:
    servers: localhost:8124
    context: default
    component-name: restaurant-service
    enabled: true
  serializer:
    general: jackson

server:
  port: 8084

# Security configuration
spring:
  security:
    user:
      name: restaurant-user
      password: restaurant-pass
      roles: USER